import Infra

/-!
  # Example: declare and push a single Scaleway queue

  The counterpart to `example/ScalewayPull.lean`. That one lists whatever
  Scaleway already has; this one declares a target — one `.queues` resource —
  and reconciles it, going through the `Keys`/`Plan`/`push` path rather than a
  raw `Backend.list`.

  It is also the shortest thing in the repo, and that is the point: the whole
  declaration is three lines. It used to be about fifty — a hand-rolled
  `inductive` key with a proved `Finite` instance, a `(provider, kind)` table,
  a `Keys` record, a `Plan` match, hand-built `Backends`, and its own argument
  parsing. Every one of those is now either generated by `fleet` or supplied by
  `Infra.Cli`. `Infra/Demo.lean` still shows the long-hand version, for anyone
  who wants to see what is underneath.

  Scaleway-only: `Infra.Cli` authenticates just the clouds a fleet declares
  into, so no AWS credentials are read or required, and `.aws .queues` is
  `Nothing` in this fleet's key family — the plan cannot mention it even by
  mistake.

  Run with:

      lake exe scaleway-queue              -- offline: the plan, from placeholders
      lake exe scaleway-queue plan         -- reads the account
      lake exe scaleway-queue apply        -- actually creates the queue

  A real, billable queue in `fr-par`, because `in paris` below says so rather
  than leaving it to whatever region your credentials name. Delete it from the
  Queues console when you are done — removing the line above un-manages it
  rather than deleting it.

  Scaleway is in Paris, Amsterdam, Warsaw and (since March 2026) Milan, so
  `in amsterdam` and `in warsaw` are equally legal *here* and would both be
  compile errors in `example/CrossCloud.lean`, which also uses AWS. That is
  the whole of the placement check: it is about the clouds the fleet declares
  into, not about the place alone.

  To have it refuse to run against the wrong organization:

      export INFRA_EXPECT_SCALEWAY_ORG=<your-org-id>
-/
open Infra.Core
open Infra.Specs

fleet exampleQueue in paris where
  resource scaleway queues "infra-example"
    { visibilityTimeoutSec := 30 }

-- One cloud, so one region, and it is `fr-par`.
#guard (exampleQueue.regions.region .scaleway).map Region.code = some "fr-par"
#guard exampleQueue.regions.covers exampleQueue.keys

-- Legal here and not in a fleet that also uses AWS.
#guard Locality.warsaw.covers exampleQueue.keys = true

def main (args : List String) : IO UInt32 := do
  Infra.Cli.run "scaleway-queue" exampleQueue.plan
    (forgets := exampleQueue.forgets)
    (accounts := ← Infra.Cli.Accounts.fromEnv)
    (regions := exampleQueue.regions) (args := args)
