import Infra

/-!
  # Example: declare and push a single Scaleway queue

  The counterpart to `example/ScalewayPull.lean`. That one lists whatever
  Scaleway already has; this one declares a target — one `.queues` resource —
  and reconciles it, going through the `Keys`/`Plan`/`push` path rather than a
  raw `Backend.list`.

  It is also the shortest thing in the repo, and that is the point: the whole
  declaration is three lines. It used to be about fifty — a hand-rolled
  `inductive` key with a proved `Finite` instance, a `(provider, kind)` table,
  a `Keys` record, a `Plan` match, hand-built `Backends`, and its own argument
  parsing. Every one of those is now either generated by `fleet` or supplied by
  `Infra.Cli`. `Infra/Demo.lean` still shows the long-hand version, for anyone
  who wants to see what is underneath.

  Scaleway-only: `Infra.Cli` authenticates just the clouds a fleet declares
  into, so no AWS credentials are read or required, and `.aws .queues` is
  `Nothing` in this fleet's key family — the plan cannot mention it even by
  mistake.

  Run with:

      lake exe scaleway-queue              -- offline: the plan, from placeholders
      lake exe scaleway-queue plan         -- reads the account
      lake exe scaleway-queue apply        -- actually creates the queue

  A real, billable queue, in whatever region your credentials name. Delete it
  from the Queues console when you are done — removing the line above
  un-manages it rather than deleting it.

  To have it refuse to run against the wrong organization:

      export INFRA_EXPECT_SCALEWAY_ORG=<your-org-id>
-/
open Infra.Core
open Infra.Specs

fleet exampleQueue where
  resource scaleway queues "infra-example"
    { visibilityTimeoutSec := 30 }

def main (args : List String) : IO UInt32 := do
  Infra.Cli.run "scaleway-queue" exampleQueue.plan
    (accounts := ← Infra.Cli.Accounts.fromEnv) (args := args)
